config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :autors
  resources :genres
  resources :books
  resources :notes
  resources :tasks
  resources :clients, only: [:new, :create]
  root 'clients#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/autor.rb
class Autor < ApplicationRecord
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :set_autor, only: [:show, :edit, :update, :destroy]

  # GET /autors
  # GET /autors.json
  def index
    @autors = Autor.all
  end

  # GET /autors/1
  # GET /autors/1.json
  def show
  end

  # GET /autors/new
  def new
    @autor = Autor.new
  end

  # GET /autors/1/edit
  def edit
  end

  # POST /autors
  # POST /autors.json
  def create
    @autor = Autor.new(autor_params)

    respond_to do |format|
      if @autor.save
        format.html { redirect_to @autor, notice: 'Autor was successfully created.' }
        format.json { render :show, status: :created, location: @autor }
      else
        format.html { render :new }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autors/1
  # PATCH/PUT /autors/1.json
  def update
    respond_to do |format|
      if @autor.update(autor_params)
        format.html { redirect_to @autor, notice: 'Autor was successfully updated.' }
        format.json { render :show, status: :ok, location: @autor }
      else
        format.html { render :edit }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1
  # DELETE /autors/1.json
  def destroy
    @autor.destroy
    respond_to do |format|
      format.html { redirect_to autors_url, notice: 'Autor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autor
      @autor = Autor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autor_params
      params.require(:autor).permit(:autor_name, :autor_year)
    end
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/views/autors/_form.html.erb
<%= form_with(model: autor, local: true) do |form| %>
  <% if autor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(autor.errors.count, "error") %> prohibited this autor from being saved:</h2>

      <ul>
      <% autor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :autor_name %>
    <%= form.text_field :autor_name, id: :autor_autor_name %>
  </div>

  <div class="field">
    <%= form.label :autor_year %>
    <%= form.number_field :autor_year, id: :autor_autor_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h1>Editing Autor</h1>

<%= render 'form', autor: @autor %>

<%= link_to 'Show', @autor %> |
<%= link_to 'Back', autors_path %>

app/views/autors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Autors</h1>

<table>
  <thead>
    <tr>
      <th>Autor name</th>
      <th>Autor year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autors.each do |autor| %>
      <tr>
        <td><%= autor.autor_name %></td>
        <td><%= autor.autor_year %></td>
        <td><%= link_to 'Show', autor %></td>
        <td><%= link_to 'Edit', edit_autor_path(autor) %></td>
        <td><%= link_to 'Destroy', autor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Autor', new_autor_path %>

app/views/autors/new.html.erb
<h1>New Autor</h1>

<%= render 'form', autor: @autor %>

<%= link_to 'Back', autors_path %>

app/views/autors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor name:</strong>
  <%= @autor.autor_name %>
</p>

<p>
  <strong>Autor year:</strong>
  <%= @autor.autor_year %>
</p>

<%= link_to 'Edit', edit_autor_path(@autor) %> |
<%= link_to 'Back', autors_path %>